### ISSUE TITLE
The next/previous icon is not centered

### ISSUE THREAD

**Issue by rafid059** [jpdias/portfolio-photo#4]
Here is a screenshot:  

![2016-03-21-224224_108x116_scrot](https://cloud.githubusercontent.com/assets/6932350/13926436/8587fe66-efb6-11e5-9c80-b8449a51bd2d.png)

**Comment by DDuarte** [comment]
What browser are you using?
It's centered on Chrome 50 ![](http://i.imgur.com/f625FXk.png)

**Comment by rafid059** [comment]
I am using Chrome 47
