### ISSUE TITLE
Issue in menu and page display in mobile

### ISSUE THREAD

**Issue by GKNSB** [jpdias/portfolio-photo#6]
Hello there mate. I've identified an issue with the page.

When you get in the page from a mobile client the page renders fine. Then click on the menu, sellect a category, images load as expected.
The issue appears when you click on the menu for a second time and select another category. The side menu doesn't close and the page scrolls down to that menu item.

You can reproduce it with the following steps.
* Visit http://jpdias.me/portfolio-photo/ from a mobile browser
* Click on the menu
* Select "Architecture"
* Click on the menu again
* Select "People"

I've tested it with latest Chrome on Android 8.1. I hope you figure it out.

**Comment by jpdias** [comment]
@GKNSB this issue must now be resolved. Feel free to re-open if there's any issue remaining. Thanks.
